Fixed : hardcode time sleep

diff --git a/.github/workflows/adapter-test.yml b/.github/workflows/adapter-test.yml
--- a/.github/workflows/adapter-test.yml
+++ b/.github/workflows/adapter-test.yml
@@ -107,16 +107,17 @@ jobs:
         
       - name: Waiting app to be ready
         if: 'inputs.waiting-app-start'
-        run: |
-          for i in {1..30}; do 
-            timeout 1 curl -I -s localhost:80 |grep 200 >/dev/null  && exit 0 || true; 
-            sleep 2; 
-            #
-            if [[ "$i" == 15 ]]; then
-              echo "App FAILED to start! Exit now.";
-              exit 1
-            fi
-          done
+        run: sleep 60
+#        run: |
+#          for i in {1..30}; do
+#            timeout 1 curl -I -s localhost:80 |grep 200 >/dev/null  && exit 0 || true;
+#            sleep 2;
+#            #
+#            if [[ "$i" == 15 ]]; then
+#              echo "App FAILED to start! Exit now.";
+#              exit 1
+#            fi
+#          done
 
       - name: Run testing with testing image
         shell: bash {0}
